command: ['uvicorn', 'app:app', '--host', '0.0.0.0', '--port', '8000']

env:
  - name: 'GENIE_SPACE_ID'
    value: '01f1b906cf2d15b4b1c72c3b25ddb2f0'
  - name: 'WAREHOUSE_ID'
    value: '38762a7d9e9e5b33'
  - name: 'LAKEBASE_HOST'
    value: 'ep-royal-silence-d24b1cks.database.us-east-1.cloud.databricks.com'
  - name: 'LAKEBASE_DB'
    value: 'retail'
  - name: 'LAKEBASE_ENDPOINT'
    value: 'projects/fe-bar-varejo/branches/production/endpoints/primary'
